// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import RecentSoldToast from "@/components/cart/RecentSoldToast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         <RecentSoldToast />
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import RecentSoldToast from "@/components/cart/RecentSoldToast";
import WhatsAppFloat from "@/components/WhatsAppFloat";
import AIStylist from "@/components/ai/AiStylist";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_APP_URL || "https://lyvera-thrift-ihvf.vercel.app",
  ),
  title: {
    default: "Lyvera Thrift | Curated Vintage & Sustainable Fashion",
    template: "%s | Lyvera Thrift", // This allows sub-pages to have titles like "Denim | Lyvera Thrift"
  },
  description:
    "Discover hand-picked, one-of-one vintage treasures and sustainable fashion at Lyvera. Salvaged silhouettes for the modern stylist.",
  keywords: [
    "thrift store",
    "vintage clothing",
    "sustainable fashion",
    "second hand luxury",
    "Nairobi fashion",
    "curated thrift",
  ],
  authors: [{ name: "Lyvera" }],
  creator: "Lyvera",
  openGraph: {
    type: "website",
    locale: "en_KE",
    url: "https://lyvera-thrift.vercel.app", // Update with your actual domain later
    siteName: "Lyvera Thrift",
    title: "Lyvera Thrift | Hand-Selected Vintage Curation",
    description:
      "One-of-one treasures salvaged for the modern stylist. Shop the latest drop.",
    images: [
      {
        url: "/og-image.jpg", // Create a 1200x630 image and put it in your public folder
        width: 1200,
        height: 630,
        alt: "Lyvera Thrift Collection",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Lyvera Thrift",
    description: "Curated vintage and sustainable fashion.",
    images: ["/og-image.jpg"],
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <RecentSoldToast />
        <WhatsAppFloat />
        <AIStylist />
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
